
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljidfxjnnoivdmdyzdgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqaWRmeGpubm9pdmRtZHl6ZGd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1OTgzOTYsImV4cCI6MjA2MjE3NDM5Nn0.QcYOm00q_DXdAUhHBmqU_MJC25S6RiRZzTd8N2fidKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);